export const FOUR_REGN_SHOPIFY_COLLECTION_DESCRIPTIONS: Record<string, string> = {
  "2 PIECE SETS": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "4REGN X LAVISH COLLECTION": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "BACK & FRONT PRINTED HOODIES": "<p><span style=\"color: #ff0000;\"><em><strong>BUY 2 FOR R699!</strong></em></span></p>\n<p><span><em>discount will be applied at checkout</em></span></p>\n<p><em><span><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>\n<p><em><br></em></p>",
  "BAGS": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "BEANIES": "<p><span style=\"font-size: 0.875rem;\"><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em>!</span><br></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "BUTTONED SHIRTS": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "CACTUS JACK SWEATPANTS": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>\n<p> </p>",
  "CAPS": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "CUSTOM": "<p><span style=\"font-size: 0.875rem;\"><em><span style=\"color: #000000;\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></span></p>\n<p><span style=\"font-size: 0.875rem;\">Want to stand out? We also offer custom printing. With high quality, durable DTF printing. Upload the picture you’d like to get printed on your hoodie/tee/sweater/cap/side bag. Place where you’d like the picture to be printed, leave any special instructions if there’s anything you’d like for us to note, add to your chart. And proceed to check out. And we will get it done and sent to you! </span></p>\n<p><em></em><em><span>our entire collection is unisex. Accomodating both 4regn men &amp; women!</span></em></p>",
  "CUSTOM PRINTED HOODIES": "<p><em><span style=\"color: #000000;\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p>Want to stand out? We also offer custom printing. With high quality, durable DTF printing. Upload the picture you’d like to get printed on your hoodie/tee. Choose your color and size. Add any special instructions and we will get it done. </p>\n<p> </p>\n<p><em>the maximum print size is A4 which is 21cm width and 29cm length </em></p>\n<p><em><span>our entire collection is unisex. Accommodating both 4regn men &amp; women!</span></em></p>",
  "CUSTOM PRINTED TEES": "<p><em><span style=\"color: #000000;\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p>Want to stand out? We also offer custom printing. With high quality, durable DTF printing. Upload the picture you’d like to get printed on your hoodie. Place where you’d like the picture to be printed, leave any special instructions if there’s anything you’d like for us to note, add to your chart. And proceed to check out. And we will get it done and sent to you! </p>\n<p><em>the maximum print size is A4 which is 21cm width and 29cm length </em></p>\n<p><em><span>our entire collection is unisex. Accommodating both 4regn men &amp; women!</span></em></p>",
  "CUSTOM SIDE BAGS": "<p><span style=\"font-size: 0.875rem;\"><em><span style=\"color: #000000;\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></span></p>\n<p><span style=\"font-size: 0.875rem;\">Want to stand out? We also offer custom printing. With high quality, durable DTF printing. Upload the picture you’d like to get printed on your side bag. Place where you’d like the picture to be printed, leave any special instructions if there’s anything you’d like for us to note, add to your chart. And proceed to check out. And we will get it done and sent to you! </span></p>\n<p><em></em><em><span>our entire collection is unisex. Accommodating both 4regn men &amp; women!</span></em></p>",
  "CUSTOM SWEATERS": "<p><span style=\"font-size: 0.875rem;\"><em><span style=\"color: #000000;\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></span></p>\n<p><span style=\"font-size: 0.875rem;\">Want to stand out? We also offer custom printing. With high quality, durable DTF printing. Upload the picture you’d like to get printed on your trucker cap. Place where you’d like the picture to be printed, leave any special instructions if there’s anything you’d like for us to note, add to your chart. And proceed to check out. And we will get it done and sent to you! </span></p>\n<p><em></em><em><span>our entire collection is unisex. Accommodating both 4regn men &amp; women!</span></em></p>",
  "CUSTOM TRUCKER CAPS": "<p><span style=\"font-size: 0.875rem;\"><em><span style=\"color: #000000;\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></span></p>\n<p><span style=\"font-size: 0.875rem;\">Want to stand out? We also offer custom printing. With high quality, durable DTF printing. Upload the picture you’d like to get printed on your trucker cap. Place where you’d like the picture to be printed, leave any special instructions if there’s anything you’d like for us to note, add to your chart. And proceed to check out. And we will get it done and sent to you! </span></p>\n<p><em></em><em><span>our entire collection is unisex. Accommodating both 4regn men &amp; women!</span></em></p>",
  "GRAPHIC HOODIES": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "GRAPHIC TEES NEW EDITION": "<div>\n<meta charset=\"UTF-8\">\n<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>\n</div>\n<p> </p>\n<p> </p>",
  "JACKETS": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "Men 2PC Sets": "<p>Discover our collection of men's 2-piece sets featuring premium quality coordinated outfits and contemporary styles.</p>",
  "Men Accessories": "<p>Discover our collection of men's accessories featuring premium quality items and contemporary styles.</p>",
  "Men Bags": "<p>Explore our collection of men's bags featuring premium quality accessories and contemporary styles.</p>",
  "Men Bottoms": "<p>Discover our collection of men's bottoms featuring premium quality pants and contemporary styles.</p>",
  "Men Caps": "<p>Explore our collection of men's caps featuring premium quality headwear and contemporary styles.</p>",
  "Men Hoodies": "<p>Discover our collection of men's hoodies featuring premium quality and contemporary styles.</p>",
  "Men Jackets": "<p>Explore our collection of men's jackets featuring premium quality outerwear and contemporary styles.</p>",
  "Men Shirts": "<p>Discover our collection of men's button shirts featuring premium quality and contemporary styles.</p>",
  "Men Shoes": "<p>Explore our collection of men's shoes featuring premium quality footwear and contemporary styles.</p>",
  "Men Sunglasses": "<p>Discover our collection of men's sunglasses featuring premium quality eyewear and contemporary styles.</p>",
  "Men Sweaters": "<p>Explore our collection of men's sweaters featuring premium quality knitwear and contemporary styles.</p>",
  "Men Tops": "<p>Explore our collection of men's tops featuring premium quality and contemporary styles.</p>",
  "MFUDUMALO COMBOS": "<p>Mfudumalo Combo’s are a collection of versatile looks that are great for the cold and cool humidity. They are crafted by @anclothing_za from Durban. The Word “Mfudumalo “ simply means “warmth”.</p>",
  "NEW ARRIVALS": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>",
  "OVERSIZED PREMIUM TEES": "<p><strong>WINTER SALE!!!</strong></p>\n<p><span style=\"color: rgb(241, 14, 14);\"><strong>BUY 2 GET 1 FREE — 3 TEES FOR R700!!</strong></span></p>\n<p><span style=\"color: #000000;\"><em>discount will be applied at checkout</em></span></p>\n<p><em><span style=\"color: #000000;\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "PANTS": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "PLAIN CLOTHING": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "PLAIN OVERSIZED DROP SHOULDER TEES": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "SHOES": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>",
  "Shop All Men": "<p>Explore our complete collection of men's apparel and accessories featuring premium quality and contemporary styles.</p>",
  "Shop All Women": "<p>Explore our complete collection of women's apparel and accessories featuring premium quality and contemporary styles.</p>",
  "SHORTS": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "SIDEBAGS": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "STANDARD GRAPHIC HOODIES": "<p><span style=\"color: #ff0000;\"><em><strong>BUY 2 FOR R599!</strong></em></span></p>\n<p><em>discount will automatically be applied at checkout</em></p>\n<p><em>offer valid til 30 Nov 23:59</em></p>",
  "STANDARD GRAPHIC TEES": "<p><span style=\"color: #ff0000;\"><em><strong>BUY 2 FOR R349!</strong></em></span></p>\n<p><em>discount will automatically be applied at checkout</em></p>\n<p><em><span style=\"color: #000000;\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "SWEATERS": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "SWEATPANTS": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "TRAVIS SCOTT CACTUS JACK COLLECTION TEES": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "TRUCKER CAPS & BEANIES": "<p><em><span style=\"color: rgb(0, 0, 0);\"><strong>FREE DELIVERY NATIONWIDE</strong></span></em></p>\n<p><em>our entire collection is unisex. Accommodating both men &amp; women</em></p>",
  "WINTER ESSENTIALS": "<p>Our curated edit of winter essentials — shop hoodies, sweaters, and everything you need for the season.</p>",
  "Women 2PC Sets": "<p>Discover our collection of women's 2-piece sets featuring premium quality coordinated outfits and contemporary styles.</p>",
  "Women Accessories": "<p>Discover our collection of women's accessories featuring premium quality items and contemporary styles.</p>",
  "Women Bags": "<p>Explore our collection of women's bags featuring premium quality accessories and contemporary styles.</p>",
  "Women Bottoms": "<p>Discover our collection of women's bottoms featuring premium quality pants and contemporary styles.</p>",
  "Women Caps": "<p>Explore our collection of women's caps featuring premium quality headwear and contemporary styles.</p>",
  "Women Dresses": "<p>Discover our collection of women's dresses featuring premium quality and contemporary styles.</p>",
  "Women Hoodies": "<p>Discover our collection of women's hoodies featuring premium quality and contemporary styles.</p>",
  "Women Jackets": "<p>Explore our collection of women's jackets featuring premium quality outerwear and contemporary styles.</p>",
  "Women Shoes": "<p>Explore our collection of women's shoes featuring premium quality footwear and contemporary styles.</p>",
  "Women Sunglasses": "<p>Discover our collection of women's sunglasses featuring premium quality eyewear and contemporary styles.</p>",
  "Women Sweaters": "<p>Explore our collection of women's sweaters featuring premium quality knitwear and contemporary styles.</p>",
  "Women Tops": "<p>Explore our collection of women's tops featuring premium quality and contemporary styles.</p>",
  "ALL MEN": "<p>Explore our complete collection of men's apparel and accessories featuring premium quality and contemporary styles.</p>",
  "ALL WOMEN": "<p>Explore our complete collection of women's apparel and accessories featuring premium quality and contemporary styles.</p>"
};

Object.assign(FOUR_REGN_SHOPIFY_COLLECTION_DESCRIPTIONS, {
  "20-29% Off": "<p>Shop selected 4REGN products with savings from 20% to 29%.</p>",
  "30-39% Off": "<p>Shop selected 4REGN products with savings from 30% to 39%.</p>",
  "40% Off & Over": "<p>Shop selected 4REGN products with savings of 40% or more.</p>",
  "ACCESSORIES": "<p>Complete your look with 4REGN accessories selected for everyday streetwear styling.</p>",
  "Brand New": "<p>Discover brand-new 4REGN products and the latest additions to the store.</p>",
  "DRESSES": "<p>Explore 4REGN dresses combining contemporary silhouettes with statement streetwear style.</p>",
  "KNITWEAR": "<p>Explore 4REGN knitwear made for easy layering, warmth and everyday style.</p>",
  "Sale": "<p>Shop selected 4REGN products at reduced prices while stock lasts.</p>",
  "SUMMER ESSENTIALS": "<p>Shop lightweight 4REGN products selected for warmer days and effortless everyday styling.</p>",
  "SUNGLASSES": "<p>Finish your look with 4REGN sunglasses in bold, contemporary styles.</p>",
  "Under 20% Off": "<p>Shop selected 4REGN products with savings of up to 19%.</p>",
});
