/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextRequest,NextResponse } from "next/server";
import { getAdmin } from "../../../lib/supabase-admin";
import { requireFourRegnProductionAdmin,cleanMoney,cleanText } from "../../../lib/four-regn-production";
import { DEFAULT_RETAIL_SETTINGS } from "../../../lib/four-regn-retail-calculations";
export const dynamic="force-dynamic";
const uuid=(v:unknown)=>typeof v==="string"&&/^[0-9a-f-]{36}$/i.test(v);
const integer=(v:unknown,max=100000)=>{const n=Number(v);return Number.isInteger(n)&&n>=0&&n<=max?n:null};
const timestamp=(v:unknown)=>{const d=new Date(String(v||""));return Number.isNaN(d.getTime())?new Date().toISOString():d.toISOString()};
async function activity(sellerId:string,userId:string,partnerId:string|null,action:string,details:Record<string,unknown>={}){await getAdmin().from("retail_partner_activity").insert({seller_id:sellerId,actor_user_id:userId,partner_id:partnerId,action,details});}
async function ownedPartner(sellerId:string,id:string){if(!uuid(id))return null;const{data}=await getAdmin().from("retail_partners").select("*").eq("seller_id",sellerId).eq("id",id).maybeSingle();return data;}
async function snapshot(sellerId:string){const db=getAdmin();let{data:settings}=await db.from("retail_pilot_settings").select("*").eq("seller_id",sellerId).maybeSingle();if(!settings){const r=await db.from("retail_pilot_settings").insert({seller_id:sellerId,...DEFAULT_RETAIL_SETTINGS}).select("*").single();if(r.error)throw r.error;settings=r.data;}
 const [partners,stock,recs,settlements,history]=await Promise.all([db.from("retail_partners").select("*").eq("seller_id",sellerId).order("updated_at",{ascending:false}),db.from("retail_stock_movements").select("*").eq("seller_id",sellerId).order("occurred_at",{ascending:false}),db.from("retail_reconciliations").select("*").eq("seller_id",sellerId).order("reconciled_at",{ascending:false}),db.from("retail_settlements").select("*").eq("seller_id",sellerId).order("settled_at",{ascending:false}),db.from("retail_partner_activity").select("*").eq("seller_id",sellerId).order("created_at",{ascending:false}).limit(1000)]);const error=partners.error||stock.error||recs.error||settlements.error||history.error;if(error)throw error;
 const rows=(partners.data||[]).map((p:any)=>{const moves=(stock.data||[]).filter((x:any)=>x.partner_id===p.id);const rs=(recs.data||[]).filter((x:any)=>x.partner_id===p.id);const pays=(settlements.data||[]).filter((x:any)=>x.partner_id===p.id);const latest=rs[0];return{...p,stockPlaced:moves.reduce((n:number,x:any)=>n+Number(x.quantity),0),sold:Number(latest?.units_sold||0),missing:Number(latest?.missing_damaged||0),settled:pays.reduce((n:number,x:any)=>n+Number(x.amount),0),latestNotes:latest?.notes||p.notes||"",latestAt:latest?.reconciled_at||null};});return{settings,partners:rows,stock:stock.data||[],reconciliations:recs.data||[],settlements:settlements.data||[],activity:history.data||[]};}
export async function GET(req:NextRequest){const auth=await requireFourRegnProductionAdmin(req);if(!auth.ok)return auth.response;try{return NextResponse.json(await snapshot(auth.sellerId));}catch(e:any){return NextResponse.json({error:e.message},{status:500});}}
export async function POST(req:NextRequest){const auth=await requireFourRegnProductionAdmin(req);if(!auth.ok)return auth.response;let b:any;try{b=await req.json()}catch{return NextResponse.json({error:"Invalid request"},{status:400})}const db=getAdmin(),action=cleanText(b.action,40);
 try{
  if(action==="save_settings"){const s=b.settings||{};const row={retail_price:cleanMoney(s.retail_price,129),unit_cost:cleanMoney(s.unit_cost,65),commission:cleanMoney(s.commission,30),initial_units:integer(s.initial_units)??20,minimum_sell_through:Math.min(100,cleanMoney(s.minimum_sell_through,50)),scale_sell_through:Math.min(100,cleanMoney(s.scale_sell_through,75)),weekly_units_target:cleanMoney(s.weekly_units_target,4),pilot_days:integer(s.pilot_days,3650)||30,max_shrinkage:Math.min(100,cleanMoney(s.max_shrinkage,2))};if(row.commission>row.retail_price||row.scale_sell_through<row.minimum_sell_through)return NextResponse.json({error:"Commission cannot exceed price, and Scale target must be at least the minimum target."},{status:400});const r=await db.from("retail_pilot_settings").upsert({seller_id:auth.sellerId,...row},{onConflict:"seller_id"});if(r.error)throw r.error;await activity(auth.sellerId,auth.userId,null,"Pilot settings updated",row);return NextResponse.json(await snapshot(auth.sellerId));}
  if(action==="create_partner"){const name=cleanText(b.name,160),qty=integer(b.initial_stock);if(!name||qty===null)return NextResponse.json({error:"Store name and valid initial stock are required."},{status:400});const code=`RP-${Date.now().toString(36).toUpperCase()}`;const r=await db.from("retail_partners").insert({seller_id:auth.sellerId,created_by:auth.userId,store_code:code,name,location:cleanText(b.location,180),contact_name:cleanText(b.contact_name,160),joined_on:String(b.joined_on||new Date().toISOString().slice(0,10)),notes:cleanText(b.notes,4000)}).select("*").single();if(r.error)throw r.error;if(qty>0){const m=await db.from("retail_stock_movements").insert({seller_id:auth.sellerId,partner_id:r.data.id,quantity:qty,movement_type:"handover",occurred_at:timestamp(b.joined_on),notes:"Initial pilot handover",recorded_by:auth.userId});if(m.error)throw m.error;}await activity(auth.sellerId,auth.userId,r.data.id,`${qty} tees supplied`,{quantity:qty,type:"initial"});return NextResponse.json(await snapshot(auth.sellerId));}
  const partner=await ownedPartner(auth.sellerId,b.partner_id);if(!partner)return NextResponse.json({error:"Retail partner not found"},{status:404});
  if(action==="edit_partner"){const patch:any={name:cleanText(b.name,160),location:cleanText(b.location,180),contact_name:cleanText(b.contact_name,160),notes:cleanText(b.notes,4000)};if(!patch.name)return NextResponse.json({error:"Store name is required"},{status:400});const r=await db.from("retail_partners").update(patch).eq("id",partner.id).eq("seller_id",auth.sellerId);if(r.error)throw r.error;await activity(auth.sellerId,auth.userId,partner.id,"Store details updated",patch);}
  else if(action==="set_status"){const statuses=["Active","Strong","Watch","Hold","Scale","Stopped","Archived"];if(!statuses.includes(b.status))return NextResponse.json({error:"Invalid status"},{status:400});const r=await db.from("retail_partners").update({status:b.status,archived_at:b.status==="Archived"?new Date().toISOString():null}).eq("id",partner.id);if(r.error)throw r.error;await activity(auth.sellerId,auth.userId,partner.id,`Store status changed ${partner.status} → ${b.status}`);}
  else if(action==="add_stock"){const quantity=integer(b.quantity);if(!quantity)return NextResponse.json({error:"Enter a stock quantity greater than zero"},{status:400});const r=await db.from("retail_stock_movements").insert({seller_id:auth.sellerId,partner_id:partner.id,quantity,movement_type:"replenishment",colour:cleanText(b.colour,80)||null,size:cleanText(b.size,40)||null,variation:cleanText(b.variation,100)||null,notes:cleanText(b.notes,1000),occurred_at:timestamp(b.occurred_at),recorded_by:auth.userId});if(r.error)throw r.error;await activity(auth.sellerId,auth.userId,partner.id,`${quantity} tees supplied`,{quantity,colour:b.colour||null,size:b.size||null});}
  else if(action==="reconcile"){const current=await snapshot(auth.sellerId);const p=current.partners.find((x:any)=>x.id===partner.id);const sold=integer(b.units_sold),missing=integer(b.missing_damaged);if(sold===null||missing===null||sold+missing>p.stockPlaced)return NextResponse.json({error:`Sold plus missing cannot exceed ${p.stockPlaced} supplied units.`},{status:400});if(sold<p.sold||missing<p.missing)return NextResponse.json({error:"Cumulative sold or missing totals cannot move backwards."},{status:400});const r=await db.from("retail_reconciliations").insert({seller_id:auth.sellerId,partner_id:partner.id,units_sold:sold,missing_damaged:missing,notes:cleanText(b.notes,4000),reconciled_at:timestamp(b.reconciled_at),recorded_by:auth.userId});if(r.error)throw r.error;await activity(auth.sellerId,auth.userId,partner.id,"Weekly reconciliation recorded",{units_sold:sold,missing_damaged:missing,previous_sold:p.sold,previous_missing:p.missing});}
  else if(action==="settlement"){const amount=cleanMoney(b.amount,-1);if(amount<=0)return NextResponse.json({error:"Enter a settlement amount greater than zero"},{status:400});const current=await snapshot(auth.sellerId);const p=current.partners.find((x:any)=>x.id===partner.id),s=current.settings;const liability=p.sold*(Number(s.retail_price)-Number(s.commission));if(p.settled+amount>liability+.01)return NextResponse.json({error:`This exceeds the outstanding 4REGN amount of R${Math.max(0,liability-p.settled).toFixed(2)}.`},{status:400});const r=await db.from("retail_settlements").insert({seller_id:auth.sellerId,partner_id:partner.id,amount,notes:cleanText(b.notes,1000),settled_at:timestamp(b.settled_at),recorded_by:auth.userId});if(r.error)throw r.error;await activity(auth.sellerId,auth.userId,partner.id,`R${amount.toFixed(2)} settlement recorded`,{amount});}
  else return NextResponse.json({error:"Unknown action"},{status:400});return NextResponse.json(await snapshot(auth.sellerId));
 }catch(e:any){return NextResponse.json({error:e.message||"Retail Pilot request failed"},{status:400})}
}
