"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";
import { DEFAULT_RETAIL_SETTINGS,decisionFor,partnerMetrics,pilotTotals,type RetailPartner,type RetailSettings } from "../../lib/four-regn-retail-calculations";
import styles from "./retail-pilot.module.css";
type Data={settings:RetailSettings;partners:RetailPartner[];stock:any[];reconciliations:any[];settlements:any[];activity:any[]};
type Modal="store"|"reconcile"|"stock"|"settlement"|"settings"|"history"|null;
const nowLocal=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
const money=(n:number)=>`R${Number(n||0).toLocaleString("en-ZA",{maximumFractionDigits:2})}`;
const pct=(n:number)=>`${Number(n||0).toFixed(1)}%`;
const formDefault={name:"",location:"",contact_name:"",joined_on:new Date().toISOString().slice(0,10),initial_stock:20,notes:""};
export default function RetailPilotClient(){const router=useRouter();const[data,setData]=useState<Data|null>(null);const[token,setToken]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[toast,setToast]=useState("");const[modal,setModal]=useState<Modal>(null);const[selected,setSelected]=useState<RetailPartner|null>(null);const[form,setForm]=useState<any>(formDefault);const[busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session){router.replace(`/login?next=${encodeURIComponent("/retail-pilot")}`);return}setToken(session.access_token);try{const r=await fetch("/api/retail-pilot",{headers:{Authorization:`Bearer ${session.access_token}`},cache:"no-store"});const j=await r.json();if(r.status===401){router.replace(`/login?next=${encodeURIComponent("/retail-pilot")}`);return}if(!r.ok)throw new Error(j.error||"Could not open Retail Pilot");setData(j)}catch(e:any){setError(e.message)}finally{setLoading(false)}})()},[router]);
 const api=async(payload:any)=>{setBusy(true);try{const r=await fetch("/api/retail-pilot",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not save");setData(j);setModal(null);setToast("Saved ✓");setTimeout(()=>setToast(""),2200)}catch(e:any){setToast(e.message);setTimeout(()=>setToast(""),4000)}finally{setBusy(false)}};
 const settings=data?.settings||DEFAULT_RETAIL_SETTINGS;const active=(data?.partners||[]).filter(p=>p.status!=="Archived");const totals=useMemo(()=>pilotTotals(active,settings),[active,settings]);const sellThrough=totals.stock?totals.sold/totals.stock*100:0;
 const openStore=(p?:RetailPartner)=>{setSelected(p||null);setForm(p?{name:p.name,location:p.location,contact_name:p.contact_name,notes:p.notes}:{...formDefault,initial_stock:settings.initial_units});setModal("store")};
 const openAction=(kind:Modal,p:RetailPartner)=>{setSelected(p);if(kind==="reconcile")setForm({units_sold:p.sold,missing_damaged:p.missing,notes:p.latestNotes||"",reconciled_at:nowLocal()});if(kind==="stock")setForm({quantity:1,colour:"",size:"",variation:"",notes:"",occurred_at:nowLocal()});if(kind==="settlement")setForm({amount:"",notes:"",settled_at:nowLocal()});setModal(kind)};
 if(loading)return <div className={styles.loading}>Opening 4REGN Retail Partners…</div>;if(error||!data)return <div className={styles.loading}><div><b>Retail Pilot could not open.</b><p>{error}</p></div></div>;
 return <main className={styles.page}><div className={styles.app}>
  <header className={styles.top}><button onClick={()=>router.push("/dashboard")}>← Dashboard</button><b>4REGN Retail Partners</b><button onClick={()=>{setForm({...settings});setModal("settings")}}>Settings</button></header>
  <section className={styles.hero}><div className={styles.eyebrow}>4REGN • Plain Tee Retail Pilot</div><h1>Prove the model.<br/>Then scale it.</h1><p>Track every retailer, tee, reconciliation and rand owed to 4REGN in one private operating view.</p><div className={styles.actions}><button className={styles.btn} onClick={()=>openStore()}>+ Add Pilot Store</button><button className={`${styles.btn} ${styles.dark}`} onClick={()=>{setForm({...settings});setModal("settings")}}>Pilot Settings</button></div></section>
  <section className={styles.card}><h2>Pilot scoreboard</h2><p className={styles.sub}>Live results across every participating store.</p><div className={styles.stats}>{[["Stores testing",active.length],["Units placed",totals.stock],["Units sold",totals.sold],["Remaining",totals.remaining],["Sell-through",pct(sellThrough)],["Retail revenue",money(totals.revenue)],["Store commissions",money(totals.commission)],["4REGN share",money(totals.owed+totals.settled)],["Owed to 4REGN",money(totals.owed)],["Already settled",money(totals.settled)],["Gross profit",money(totals.profit)],["Missing / damaged",totals.missing]].map(([l,v])=><div className={styles.stat} key={l}><small>{l}</small><b>{v}</b></div>)}</div></section>
  <div className={styles.grid}><section className={styles.card}><h2>{settings.pilot_days}-day targets</h2><Rows rows={[["Initial stock",`${settings.initial_units} tees`],["Minimum sell-through",pct(settings.minimum_sell_through)],["Scale target",pct(settings.scale_sell_through)],["Weekly velocity",`${settings.weekly_units_target} units`],["Shrinkage target",`≤${settings.max_shrinkage}%`]]}/></section><section className={styles.card}><h2>Unit economics</h2><Rows rows={[["Retail price",money(settings.retail_price)],["Store commission",money(settings.commission)],["4REGN receives",money(settings.retail_price-settings.commission)],["Unit cost",money(settings.unit_cost)],["Gross profit / tee",money(settings.retail_price-settings.commission-settings.unit_cost)]]}/></section></div>
  <section className={styles.card}><div className={styles.sectionHead}><div><h2>Retail partners</h2><p className={styles.sub}>Each store is measured separately.</p></div><button className={styles.btn} onClick={()=>openStore()}>+ Store</button></div><div className={styles.storeList}>{!active.length?<div className={styles.empty}>Add the first retailer when you hand over pilot stock.</div>:active.map(p=><StoreCard key={p.id} p={p} settings={settings} onAction={openAction} onEdit={openStore} onStatus={(status:string)=>api({action:"set_status",partner_id:p.id,status})}/>)}</div></section>
  <div className={styles.grid}><section className={styles.card}><h2>Decision framework</h2><Decision sellThrough={sellThrough} settings={settings} shrinkage={totals.stock?totals.missing/totals.stock*100:0}/></section><section className={styles.card}><h2>What we are learning</h2><Rows rows={[["Demand","Do customers buy at this price?"],["Velocity","Units moved per week"],["Product mix","Colours and sizes that move"],["Partner quality","Reporting and settlement discipline"],["Economics","Profit versus capital and admin"]]}/></section></div>
  <section className={styles.card}><h2>Pilot roadmap</h2><div className={styles.roadmap}>{[["Week 0","Handover inventory and agree retail terms."],["Week 1","First reconciliation, sales and customer feedback."],["Week 2","Second settlement; replenish strong sizes only."],["Week 3","Test whether demand survives launch novelty."],["Day 30","Final count and Scale / Hold / Stop decision."]].map(([a,b])=><div key={a}><b>{a}</b><span>{b}</span></div>)}</div></section>
 </div>{modal&&<ModalShell title={modalTitle(modal,selected)} onClose={()=>setModal(null)}>{modal==="store"?<StoreForm form={form} setForm={setForm} editing={!!selected} busy={busy} onSave={()=>api(selected?{action:"edit_partner",partner_id:selected.id,...form}:{action:"create_partner",...form})}/>:modal==="settings"?<SettingsForm form={form} setForm={setForm} busy={busy} onSave={()=>api({action:"save_settings",settings:form})}/>:modal==="history"?<History data={data} partner={selected!}/>:<ActionForm kind={modal} form={form} setForm={setForm} busy={busy} partner={selected!} settings={settings} onSave={()=>api({action:modal,partner_id:selected!.id,...form})}/>}</ModalShell>}{toast&&<div className={styles.toast}>{toast}</div>}</main>}
function StoreCard({p,settings,onAction,onEdit,onStatus}:any){const m=partnerMetrics(p,settings),d=decisionFor(m,settings);return <article className={styles.store}><div className={styles.storeHead}><div><span className={`${styles.badge} ${styles[d.key]}`}>{d.label}</span><h3>{p.name}</h3><p>{p.location||"Location not added"} • {p.store_code}</p></div><strong>{pct(m.sellThrough)}</strong></div><div className={styles.miniGrid}>{[["Stock placed",p.stockPlaced],["Sold",p.sold],["Remaining",m.remaining],["Missing",p.missing],["Store earned",money(m.storeCommission)],["Gross profit",money(m.grossProfit)],["OWED TO 4REGN",money(m.outstanding)],["Shrinkage",pct(m.shrinkage)]].map(([l,v])=><div key={l} className={l==="OWED TO 4REGN"?styles.owed:""}><small>{l}</small><b>{v}</b></div>)}</div><div className={styles.progress}><span style={{width:`${Math.min(100,m.sellThrough)}%`}}/></div>{p.latestNotes&&<div className={styles.notice}>{p.latestNotes}</div>}<div className={styles.actions}><button className={styles.btn} onClick={()=>onAction("reconcile",p)}>Weekly Update</button><button onClick={()=>onAction("settlement",p)}>Settlement</button><button onClick={()=>onAction("stock",p)}>Add Stock</button><button onClick={()=>onAction("history",p)}>History</button><button onClick={()=>onEdit(p)}>Edit</button><select value={p.status} onChange={e=>onStatus(e.target.value)}>{["Active","Strong","Watch","Hold","Scale","Stopped","Archived"].map(x=><option key={x}>{x}</option>)}</select></div></article>}
function Rows({rows}:any){return <div className={styles.rows}>{rows.map(([a,b]:any)=><div key={a}><span><b>{a}</b></span><strong>{b}</strong></div>)}</div>}
function Decision({sellThrough,settings,shrinkage}:any){const key=sellThrough>=settings.scale_sell_through&&shrinkage<=settings.max_shrinkage?"scale":sellThrough>=settings.minimum_sell_through?"hold":"watch";return <div className={`${styles.decision} ${styles[key]}`}><h3>{key==="scale"?"SCALE SIGNAL":key==="hold"?"HOLD & PROVE":"BELOW TARGET / WATCH"}</h3><p>{key==="scale"?"The pilot has reached the scale target. Confirm settlement discipline and shrinkage before expanding.":key==="hold"?"Continue testing for another reconciliation cycle before expanding.":"Diagnose price, product, presentation, location and customer fit before adding stores."}</p></div>}
function ModalShell({title,onClose,children}:any){return <div className={styles.backdrop}><div className={styles.modal}><header><div><h2>{title}</h2><p className={styles.sub}>All changes save securely to the 4REGN pilot.</p></div><button onClick={onClose}>×</button></header>{children}</div></div>}
const Field=({label,children}:any)=><label className={styles.field}><span>{label}</span>{children}</label>;
function StoreForm({form,setForm,editing,busy,onSave}:any){return <><div className={styles.form}><Field label="Store name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Location"><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></Field><Field label="Contact / person"><input value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})}/></Field>{!editing&&<><Field label="Date joined"><input type="date" value={form.joined_on} onChange={e=>setForm({...form,joined_on:e.target.value})}/></Field><Field label="Initial stock"><input type="number" min="0" value={form.initial_stock} onChange={e=>setForm({...form,initial_stock:Number(e.target.value)})}/></Field></>}</div><Field label="Notes"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><button className={styles.save} disabled={busy} onClick={onSave}>{busy?"Saving…":editing?"Save Store":"Add Pilot Store"}</button></>}
function SettingsForm({form,setForm,busy,onSave}:any){const fs=[["retail_price","Retail price"],["unit_cost","Unit production cost"],["commission","Store commission"],["initial_units","Initial units / store"],["minimum_sell_through","Minimum sell-through %"],["scale_sell_through","Scale sell-through %"],["weekly_units_target","Weekly units target"],["pilot_days","Pilot duration (days)"],["max_shrinkage","Maximum shrinkage %"]];return <><div className={styles.form}>{fs.map(([k,l])=><Field label={l} key={k}><input type="number" min="0" value={form[k]} onChange={e=>setForm({...form,[k]:Number(e.target.value)})}/></Field>)}</div><button className={styles.save} disabled={busy} onClick={onSave}>Save Settings</button></>}
function ActionForm({kind,form,setForm,busy,partner,settings,onSave}:any){if(kind==="reconcile")return <><div className={styles.form}><Field label="Total units sold"><input type="number" min={partner.sold} max={partner.stockPlaced-partner.missing} value={form.units_sold} onChange={e=>setForm({...form,units_sold:Number(e.target.value)})}/></Field><Field label="Missing / damaged"><input type="number" min={partner.missing} value={form.missing_damaged} onChange={e=>setForm({...form,missing_damaged:Number(e.target.value)})}/></Field><Field label="Date and time"><input type="datetime-local" value={form.reconciled_at} onChange={e=>setForm({...form,reconciled_at:e.target.value})}/></Field></div><Field label="Feedback / notes"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><button className={styles.save} disabled={busy} onClick={onSave}>Save Weekly Update</button></>;if(kind==="stock")return <><div className={styles.form}><Field label="Quantity"><input type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></Field><Field label="Colour (optional)"><input value={form.colour} onChange={e=>setForm({...form,colour:e.target.value})}/></Field><Field label="Size (optional)"><input value={form.size} onChange={e=>setForm({...form,size:e.target.value})}/></Field><Field label="Variation (optional)"><input value={form.variation} onChange={e=>setForm({...form,variation:e.target.value})}/></Field><Field label="Date and time"><input type="datetime-local" value={form.occurred_at} onChange={e=>setForm({...form,occurred_at:e.target.value})}/></Field></div><Field label="Handover notes"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><button className={styles.save} disabled={busy} onClick={onSave}>Record Stock Handover</button></>;const outstanding=partnerMetrics(partner,settings).outstanding;return <><div className={styles.amount}>Outstanding: <b>{money(outstanding)}</b></div><div className={styles.form}><Field label="Payment amount"><input type="number" min="0.01" max={outstanding} value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="Payment date and time"><input type="datetime-local" value={form.settled_at} onChange={e=>setForm({...form,settled_at:e.target.value})}/></Field></div><Field label="Payment note"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><button className={styles.save} disabled={busy||outstanding<=0} onClick={onSave}>Record Settlement</button></>}
function History({data,partner}:any){const items=data.activity.filter((x:any)=>x.partner_id===partner.id);return <div className={styles.history}>{items.length?items.map((x:any)=><div key={x.id}><b>{x.action}</b><time>{new Date(x.created_at).toLocaleString("en-ZA",{timeZone:"Africa/Johannesburg"})}</time></div>):<div className={styles.empty}>No activity yet.</div>}</div>}
function modalTitle(m:Modal,p:RetailPartner|null){return m==="store"?(p?"Edit Retail Partner":"Add Pilot Store"):m==="reconcile"?"Weekly Update":m==="stock"?"Add Stock":m==="settlement"?"Record Settlement":m==="settings"?"Pilot Settings":"Store History"}
